import {
  buildEmailShell,
  paragraph,
} from "@/lib/emails/meeting";

export function buildAccountDeletedEmail() {
  const text = [
    "Your user account have been permanently deleted from our database, along with all stored data.",
    "",
    "Any scheduled meeting have been cancelled",
    "",
    "Your email was deleted immediately after this mail was sent.",
    "",
    "This is an autogenerated mail on behalf of Magnus Kongskov.",
  ].join("\n");

  const html = buildEmailShell(
    "Account deleted",
    [
      paragraph(
        "Your user account have been permanently deleted from our database, along with all stored data.",
      ),
      paragraph("Any scheduled meeting have been cancelled"),
      paragraph("Your email was deleted immediately after this mail was sent."),
      paragraph("This is an autogenerated mail on behalf of Magnus Kongskov."),
    ].join(""),
  );

  return { subject: "Your account has been deleted", text, html };
}
