import { NextResponse } from "next/server";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

type ContactRequestBody = {
  name?: string;
  email?: string;
  company?: string;
  phone?: string;
  url?: string;
  message?: string;
  phoneIncluded?: boolean;
  agreedToTerms?: boolean;
};

function formatField(value: string | undefined): string {
  const trimmed = value?.trim();
  return trimmed ? trimmed : "blank";
}

function buildEmailBody(data: ContactRequestBody): string {
  return [
    "Type: WebsiteInputFormContactRequest",
    `Name: ${formatField(data.name)}`,
    `Email: ${formatField(data.email)}`,
    `Company Name: ${formatField(data.company)}`,
    `Phone: ${formatField(data.phone)}`,
    `URL: ${formatField(data.url)}`,
    `Message: ${formatField(data.message)}`,
    `Phone included: ${data.phoneIncluded ?? false}`,
    `Agreed to terms: ${data.agreedToTerms ?? false}`,
  ].join("\n");
}

function buildAutoReplyHtml(logoUrl: string): string {
  return `<!DOCTYPE html>
<html>
<body style="font-family: sans-serif; color: #333; max-width: 600px; margin: 0 auto; padding: 24px;">
  <img src="${logoUrl}" alt="Kongskov Web Services logo" width="64" height="64" style="display: block; margin-bottom: 24px;" />
  <p>Thanks for showing interest in buying a Landing Page Review. I will get back to you as soon as possible.</p>
  <p style="color: #666; font-size: 14px; margin-top: 32px;">This is an autogenerated message on the behalf of Magnus Kongskov.</p>
</body>
</html>`;
}

const AUTO_REPLY_TEXT = `Thanks for showing interest in buying a Landing Page Review. I will get back to you as soon as possible.

This is an autogenerated message on the behalf of Magnus Kongskov.`;

export async function POST(request: Request) {
  if (!process.env.RESEND_API_KEY) {
    return NextResponse.json(
      { error: "Email service is not configured." },
      { status: 500 },
    );
  }

  let body: ContactRequestBody;

  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { error: "Invalid request body." },
      { status: 400 },
    );
  }

  const email = body.email?.trim();

  if (!email) {
    return NextResponse.json(
      { error: "Please add an email." },
      { status: 400 },
    );
  }

  if (!body.agreedToTerms) {
    return NextResponse.json(
      {
        error:
          "For legal reasons i cannot accept you information before you have agreed to the terms & privacy.",
      },
      { status: 400 },
    );
  }

  const { error } = await resend.emails.send({
    from: process.env.RESEND_FROM_EMAIL ?? "contactform@magnuskongskov.dk",
    to: "primary@magnuskongskov.dk",
    subject: "Website Contact Request",
    text: buildEmailBody(body),
  });

  if (error) {
    return NextResponse.json(
      { error: "Failed to send email. Please try again." },
      { status: 500 },
    );
  }

  const siteUrl = process.env.SITE_URL ?? "https://magnuskongskov.dk";
  const logoUrl = `${siteUrl.replace(/\/$/, "")}/cl.png`;

  await resend.emails.send({
    from: "auto@magnuskongskov.dk",
    to: email,
    subject: "Thanks for your interest – Landing Page Review",
    text: AUTO_REPLY_TEXT,
    html: buildAutoReplyHtml(logoUrl),
  });

  return NextResponse.json({ success: true });
}
