import { NextResponse } from "next/server";
import { Resend } from "resend";
import Stripe from "stripe";
import { connectDB } from "@/lib/db";
import { User } from "@/models/User";

const resend = new Resend(process.env.RESEND_API_KEY);

const PURCHASE_CONFIRMATION_TEXT = `Thank you for your purchase. I expect to deliver your detailed landing page review in 3 to 5 days. If you have any questions in the meantime feel free to contact me at primary@magnuskongskov.dk.

This is an autogenerated email on behalf on Magnus Kongskov`;

function buildPurchaseConfirmationHtml(): string {
  return `<!DOCTYPE html>
<html>
<body style="font-family: sans-serif; color: #333; max-width: 600px; margin: 0 auto; padding: 24px;">
  <p>Thank you for your purchase. I expect to deliver your detailed landing page review in 3 to 5 days. If you have any questions in the meantime feel free to contact me at primary@magnuskongskov.dk.</p>
  <p style="color: #666; font-size: 14px; margin-top: 32px;">This is an autogenerated email on behalf on Magnus Kongskov</p>
</body>
</html>`;
}

function formatAmount(
  amountTotal: number | null,
  currency: string | null,
): string {
  if (amountTotal == null || !currency) {
    return "unknown";
  }

  const value = (amountTotal / 100).toFixed(2);
  return `${value} ${currency.toUpperCase()}`;
}

async function handlePwCheckoutCompleted(session: Stripe.Checkout.Session) {
  const email =
    session.metadata?.email ??
    session.customer_details?.email ??
    session.customer_email;

  if (!email) {
    return;
  }

  await connectDB();

  const amount = formatAmount(session.amount_total, session.currency);
  const successful = session.payment_status === "paid";

  await User.findOneAndUpdate(
    { mail: email.toLowerCase() },
    {
      $set: successful ? { level: "1.3.5" } : {},
      $push: {
        transactions: {
          time: new Date(),
          amount,
          successful,
        },
      },
    },
    { upsert: true, setDefaultsOnInsert: true },
  );
}

export async function POST(request: Request) {
  if (!process.env.STRIPE_SECRET_KEY || !process.env.STRIPE_WEBHOOK_SECRET) {
    return NextResponse.json(
      { error: "Webhook is not configured." },
      { status: 500 },
    );
  }

  const body = await request.text();
  const signature = request.headers.get("stripe-signature");

  if (!signature) {
    return NextResponse.json(
      { error: "Missing Stripe signature." },
      { status: 400 },
    );
  }

  const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
  let event: Stripe.Event;

  try {
    event = stripe.webhooks.constructEvent(
      body,
      signature,
      process.env.STRIPE_WEBHOOK_SECRET,
    );
  } catch {
    return NextResponse.json({ error: "Invalid signature." }, { status: 400 });
  }

  if (event.type === "checkout.session.completed") {
    const session = event.data.object as Stripe.Checkout.Session;

    if (session.metadata?.productType === "pw") {
      try {
        await handlePwCheckoutCompleted(session);
      } catch {
        return NextResponse.json(
          { error: "Failed to update user after purchase." },
          { status: 500 },
        );
      }
    } else if (process.env.RESEND_API_KEY) {
      const customerEmail =
        session.customer_details?.email ?? session.customer_email;

      if (customerEmail) {
        const { error } = await resend.emails.send({
          from: "Magnus Kongskov <auto@magnuskongskov.dk>",
          to: customerEmail,
          subject: "Thank you for your purchase – Landing Page Review",
          text: PURCHASE_CONFIRMATION_TEXT,
          html: buildPurchaseConfirmationHtml(),
        });

        if (error) {
          return NextResponse.json(
            { error: "Failed to send confirmation email." },
            { status: 500 },
          );
        }
      }
    }
  }

  return NextResponse.json({ received: true });
}
